### ISSUE TITLE
Which versions are you using?

### ISSUE THREAD

**Issue by jfjensen** [AtsushiSakai/PyAdvancedControl#1]
Could you perhaps write in the README which versions of the various Python libraries you are using when running the tests?
I'm thinking of Numpy,Scipy, ecos, cvxpy, etc...
Thanks!

**Comment by AtsushiSakai** [comment]
@jfjensen Thank you for your interest. I added version information in README. Please check it.

**Comment by jfjensen** [comment]
Thank you!
I now managed to run the tests with:
- Python 3.5.5
- cvxpy 0.4.11 (this version is important)
- ecos 2.0.7rc2 (this version is important)
- cvxopt 1.2.0
- scipy 1.1.0
- numpy 1.15.0
- matplotlib 2.2.2

**Comment by AtsushiSakai** [comment]
@jfjensen OK. I updated README based on your test. Actually, I want to update cvxpy to v1.0 ...
